name: CI

on:
  push:
    branches:
      - main # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t cksspk/hello-github:${{ github.sha }} .
          docker tag cksspk/hello-github:${{ github.sha }} cksspk/hello-github:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push cksspk/hello-github:latest
          docker push cksspk/hello-github:${{ github.sha }}
