# 推送到 ghci， 使用 docker/metadata-action@v5

name: ci-buildx-3

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .  
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
